// i2c_io_buf.sv - I2C I/O Buffer
// Handles SCL/SDA input synchronization and output drive
// SCL/SDA are open-drain style outputs (oe=1 drives low, oe=0 releases)

module i2c_io_buf (
    input  logic clk,
    input  logic rst_n,

    // SCL (input, 2-stage sync)
    input  logic scl_i_raw,
    output logic scl_i_sync,   // synchronized scl

    // SDA (bidirectional)
    input  logic sda_i_raw,
    output logic sda_i_sync,  // synchronized sda (for reading)
    input  logic sda_o,       // data to drive onto SDA
    input  logic sda_oe,      // output enable (1=drive, 0=release)
    output logic sda_t,        // actual SDA on bus (for monitoring)

    // Master clock output (driven by clk_gen, connected to external scl)
    input  logic scl_o,
    input  logic scl_oe,      // master drives SCL when 1

    // Mode
    input  logic is_master     // 1=master, 0=slave
);

    // ============================================================
    // 2-FF Synchronizer for async inputs (scl_i, sda_i)
    // ============================================================
    // SCL sync (for slave FSM sampling)
    logic scl_meta;
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            scl_meta  <= 1'b1;  // default high (I2C idle)
            scl_i_sync <= 1'b1;
        end else begin
            scl_meta  <= scl_i_raw;
            scl_i_sync <= scl_meta;
        end
    end

    // SDA sync
    logic sda_meta;
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            sda_meta   <= 1'b1;
            sda_i_sync <= 1'b1;
        end else begin
            sda_meta   <= sda_i_raw;
            sda_i_sync <= sda_meta;
        end
    end

    // ============================================================
    // SDA output drive (open-drain)
    // sda_oe=1: drive sda_o onto bus (sda_t = sda_o)
    // sda_oe=0: release bus (sda_t = 1'bz) — pulled high externally
    // ============================================================
    assign sda_t = sda_oe ? sda_o : 1'bz;  // 'z' = high-impedance (pulled high)

    // ============================================================
    // SCL output (Master only)
    // scl_oe=1: drive scl_o onto bus
    // scl_oe=0: release (slave doesn't drive SCL)
    // In our design, scl_o is generated by clock_gen sub-module
    // ============================================================
    // SCL is also open-drain; when master scl_oe=1, scl_o drives SCL low
    // When scl_oe=0, SCL is released (pulled high externally)
    // Note: for master, scl_o toggles; for slave, scl_o = 1'bz

    // For synthesis, we model scl_t as the actual bus value
    // scl_oe=1: scl_t = scl_o (master drives)
    // scl_oe=0: scl_t = 1'bz (released, pulled high)
    // scl_i_raw samples the actual bus (for both master/slave)

endmodule
